add shouldFallbackToLatestVersion for DataObjectDocument
silverstripe/silverstripe-search-service pull request #50
Opened 2021-01-14 07:59 UTC by andrewandante

Adds provisioning for falling back to finding the latest version of a `DataObject` that may not exist any more. Fixes #49 by looking up the previously published version of the `DataObject` for its relations and data

2021-01-18 02:24 UTC, chillu requested changes

2021-01-18 02:24 UTC, chillu commented on src/DataObject/DataObjectDocument.php
> +        if (!$dataObject && $data['fallback']) {
You should check if the object is versioned here.

2021-01-21 04:03 UTC, andrewandante commented on src/DataObject/DataObjectDocument.php
> +        if (!$dataObject && $data['fallback']) {
Makes sense, though I think we've limited this to applying to Versioned objects haven't we?

2021-01-21 19:24 UTC, chillu commented on src/DataObject/DataObjectDocument.php
> +        if (!$dataObject && $data['fallback']) {
`DataObjectDocument` should be able to apply to unversioned objects as well. If you check through the code on the module, there's a few "has versioned" checks

2021-01-21 19:29 UTC, chillu approved these changes

2021-01-21 19:30 UTC, chillu commented
Looking great, thanks Andrew!

2021-01-21 19:30 UTC, merged